#format = """
#[╭─user───❯](bold blue) $username
#[┣─system─❯](bold yellow) $hostname
#[┣─project❯](bold red) $directory$rust$git_branch$git_status$package$golang$terraform$docker_context$python$docker_context$nodejs
#[╰─cmd────❯](bold green) 
#"""
#format = '$all'

#[localip]
#ssh_only = false
#format = '📟 [$localipv4](bold red) '
#disabled = false
add_newline = false

format = """$directory$character"""
right_format = """$hostname$git_branch$git_status$all"""

[hostname]
ssh_only = false
format = 'on [$hostname](yellow) '
trim_at = "."
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[❯](bold red)"
#  
# configure directory
[directory]
read_only = " "
truncation_length = 1
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "italic blue"

[git_status]
style = "purple"
disabled = false

#[cmd_duration]
#min_time = 4
#show_milliseconds = false
#disabled = false
#style = "bold red"

[aws]
symbol = "  "
disabled = true

[conda]
symbol = " "
disabled = true

[dart]
symbol = " "
disabled = true

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = true

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[git_branch]
symbol = " "
disabled = true

[golang]
symbol = " "
disabled = true

[hg_branch]
symbol = " "
disabled = true

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[memory_usage]
symbol = "󰍛 "
disabled = true

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "
disabled = true

[package]
symbol = "󰏗 "
disabled = true

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[python]
symbol = " "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[scala]
symbol = " "
disabled = true

[shlvl]
symbol = " "
disabled = true

[swift]
symbol = "ﯣ "
disabled = true

[nodejs]
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
disabled = true
